//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblOgr
    {
        public int OgrID { get; set; }
        public int OgrNumara { get; set; }
        public string OgrAd { get; set; }
        public string OgrSoyad { get; set; }
        public int OgrFakulte { get; set; }
        public int OgrBolum { get; set; }
        public int OgrBurs { get; set; }
        public int OgrBorc { get; set; }
    
        public virtual TblBolum TblBolum { get; set; }
        public virtual TblFakulte TblFakulte { get; set; }
    }
}
